import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { fonts } from "./fonts";
import { Box } from "@chakra-ui/react";
import SidebarWithHeader from "./components/Sidebar";

// Load Merriweather Font
const merriweather = Merriweather({
  weight: ["400", "700"], // Specify weights as needed
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
        <Providers>
          <Box
            bgColor={"gray.100"}
            color={"black"}
            minHeight={"100vh"}
            w={"full"}
          >
            <SidebarWithHeader>{children}</SidebarWithHeader>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
